version: "3.9"

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend-network

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
